<?php

namespace ContainerLASylV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Helper\MessageHelper' shared autowired service.
     *
     * @return \App\Helper\MessageHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Helper/MessageHelper.php';

        return $container->privates['App\\Helper\\MessageHelper'] = new \App\Helper\MessageHelper(($container->services['router'] ?? $container->getRouterService()));
    }
}
