<?php

namespace ContainerYZOpB2S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JPavGCMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JPavGCM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JPavGCM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', '.errored.rjF9Ixi', NULL, 'Cannot determine controller argument for "App\\Controller\\BlogController::post1()": the $post argument is type-hinted with the non-existent class or interface: "App\\Controller\\Post". Did you forget to add a use statement?'],
        ], [
            'post' => '?',
        ]);
    }
}
