<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQqmXay3\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQqmXay3/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQqmXay3.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQqmXay3\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQqmXay3\App_KernelProdContainer([
    'container.build_hash' => 'QqmXay3',
    'container.build_id' => '5e9f493d',
    'container.build_time' => 1646236027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQqmXay3');
