index:
    path: /
    controller: App\Controller\DefaultController::index

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact

post_list:
    path: /liste-des-articles
    controller: App\Controller\PostController::list

post_item:
    path: /article/fonctionnement-des-applications-symfony
    controller: App\Controller\DefaultController::item


post_item2:
    path: /article/fonctionnement-des-applications-symfony2
    controller: App\Controller\PostController::item2



   