<?php

namespace ContainerRX7nM6r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_EctgMSSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.EctgMSS' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Service\UserManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\AvecServiceController::deactivateUser()": the $userManager argument is type-hinted with the non-existent class or interface: "Symfony\\Bundle\\FrameworkBundle\\Service\\UserManager".');
    }
}
