<?php

namespace ContainerRX7nM6r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TVUxW0NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TVUxW0N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TVUxW0N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userManager' => ['privates', '.errored.EctgMSS', NULL, 'Cannot determine controller argument for "App\\Controller\\AvecServiceController::deactivateUser()": the $userManager argument is type-hinted with the non-existent class or interface: "Symfony\\Bundle\\FrameworkBundle\\Service\\UserManager".'],
        ], [
            'userManager' => '?',
        ]);
    }
}
