<?php

namespace ContainerDdcxsPA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3KkKd6KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3KkKd6K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3KkKd6K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userManager' => ['privates', 'App\\Service\\UserManager', 'getUserManagerService', true],
        ], [
            'userManager' => 'App\\Service\\UserManager',
        ]);
    }
}
