<?php

namespace ContainerDdcxsPA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RjF9IxiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.rjF9Ixi' shared service.
     *
     * @return \App\Controller\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\BlogController::post1()": the $post argument is type-hinted with the non-existent class or interface: "App\\Controller\\Post". Did you forget to add a use statement?');
    }
}
