<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYZOpB2S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYZOpB2S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYZOpB2S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYZOpB2S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYZOpB2S\App_KernelDevDebugContainer([
    'container.build_hash' => 'YZOpB2S',
    'container.build_id' => '6fcda480',
    'container.build_time' => 1646314820,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYZOpB2S');
