<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCFtxroV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCFtxroV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCFtxroV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCFtxroV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCFtxroV\App_KernelDevDebugContainer([
    'container.build_hash' => 'CFtxroV',
    'container.build_id' => '078a544a',
    'container.build_time' => 1646303601,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCFtxroV');
