<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xra0Sr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xra0Sr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xra0Sr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xra0Sr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0xra0Sr\App_KernelDevDebugContainer([
    'container.build_hash' => '0xra0Sr',
    'container.build_id' => '127cd34d',
    'container.build_time' => 1646301025,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xra0Sr');
