<?php

namespace ContainerLV4Vh3V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IrWOFlWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.irWOFlW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.irWOFlW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AvecServiceController::deactivateUser' => ['privates', '.service_locator.3KkKd6K', 'get_ServiceLocator_3KkKd6KService', true],
            'App\\Controller\\BlogController::post1' => ['privates', '.service_locator.JPavGCM', 'get_ServiceLocator_JPavGCMService', true],
            'App\\Controller\\MessageController::list' => ['privates', '.service_locator.Bauz967', 'get_ServiceLocator_Bauz967Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AvecServiceController:deactivateUser' => ['privates', '.service_locator.3KkKd6K', 'get_ServiceLocator_3KkKd6KService', true],
            'App\\Controller\\BlogController:post1' => ['privates', '.service_locator.JPavGCM', 'get_ServiceLocator_JPavGCMService', true],
            'App\\Controller\\MessageController:list' => ['privates', '.service_locator.Bauz967', 'get_ServiceLocator_Bauz967Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AvecServiceController::deactivateUser' => '?',
            'App\\Controller\\BlogController::post1' => '?',
            'App\\Controller\\MessageController::list' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AvecServiceController:deactivateUser' => '?',
            'App\\Controller\\BlogController:post1' => '?',
            'App\\Controller\\MessageController:list' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
