<?php

namespace ContainerLV4Vh3V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\UserManager' shared autowired service.
     *
     * @return \App\Service\UserManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/UserManager.php';

        return $container->privates['App\\Service\\UserManager'] = new \App\Service\UserManager();
    }
}
